### ISSUE TITLE
[feature][prometheus] ECS service discovery extension for prometheus

### ISSUE THREAD

**Issue by pingleig** [aws-observability/aws-otel-collector#412]
A mirror for https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1395

## Overview

An extension that calls ECS API and generates file sd targets for prometheus receiver

## TODO

Upstream PRs

- [ ] mock fetcher and docker label matcher https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2734
- [x] doc https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2377

In tree implementation (in case upstream does not have enough bandwidth to review)

- [ ] a 'next' branch for v0.9.0 release
