### ISSUE TITLE
[meta] Tracker for release 0.9.0

### ISSUE THREAD

**Issue by pingleig** [aws-observability/aws-otel-collector#418]
## Bug fixes

- exporter/awsemfexporter
   - [x] https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2512 delta and rate problem, it was breaking container insight dashboard

## New components

- [x] extension/ecsobserver #412 prometheus ecs service discovery (mark as done because we are not going to do it in this release)
- [x] receiver/cadvisor #416 (that PR seems to have more than once component)
- [x] receiver/jaeger  #354  

## Dependency update

- [x]  #417 api change in otel upstream, e.g. config etc.

## Test

 - [x] integ test for jaeger and zipkin https://github.com/aws-observability/aws-otel-test-framework/pull/261
