### ISSUE TITLE
[test] Split CI.yaml

### ISSUE THREAD

**Issue by pingleig** [aws-observability/aws-otel-collector#424]
## Background

Currently CI.yaml is too big (the problem is the matrix size is too big) and github workflow does not allow retry single job, you have to retry all  jobs in a workflow.

We should be able to split it so it's easier for debugging and retry. The main problem is there is no dependency between workflows https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482/14 However, there are workarounds to check github API for status of other workflow. https://github.com/asarkar/build-time-tracker/blob/03259fad3af0b2a44eb1a451635bb972e3930b52/.github/workflows/publish.yml#L21

## TODO

- [ ] decide how we want to split the yaml.
- [ ] allow trigger CI workflow directly with parameters to filter out test env and test cases using input, e.g. `platform=ecs, workload=trace, exporter=oltp`
- [x] when generating the matrix, only retry tests that already failed ... (might put it into the util in test framework)
   - might be able to (ab)use the cache feature https://github.com/actions/cache#skipping-steps-based-on-cache-hit
   - https://github.com/aws-observability/aws-otel-collector/pull/436 and following PRs enabled cache for most workflows
- [ ] (optional) use static matrix so we can run action locally https://github.com/nektos/act/issues/284#issuecomment-785273038 (or we can't help fix `act` but a lot of change is required in their codebase because they does not evaluate matrix using output from previous jobs).
